management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
spring:
  jmx:
    enabled: true
  datasource:
    url: jdbc:h2:mem:book_catalogue
    user: sa
    password: 1
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    rest:
      basePath: /api/v1
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  liquibase:
    change-log: classpath:db/changelog/changelog.yml
    contexts: production

logging:
  level:
    root: INFO
  file:
    name: ${java.io.tmpdir}/application.log
