spring:
  datasource:
    url: jdbc:h2:mem:book_catalogue
    user: sa
    password: 1
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  liquibase:
    change-log: classpath:db/changelog/changelog.yml
    contexts: production

logging:
  level:
    root: ERROR
