spring:
  shell:
    history:
      enabled: false
    command:
      version:
        enabled: false

  batch:
    job:
      enabled: false

  data:
    mongodb:
      database: egorin_av_booksdb
      port: 0
      host: localhost

  datasource:
    url: jdbc:h2:mem:source_db
    driverClassName: org.h2.Driver
    username: sa
    password:

  liquibase:
    change-log: classpath:db/changelog/changelog.yml
    contexts: production

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.4

logging:
  level:
    root: ERROR
