name: library-application-otus
services:
  library-app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JAVA_OPTS=-Dlogging.level.ru.otus.hw=INFO -Dlogging.level.root=WARN
    depends_on:
      - db
    networks:
      - default
      - internal-net

  db:
    container_name: postgres
    image: "postgres:16.2"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - internal-net
networks:
  internal-net:
    internal: true
